<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <PackageReference Include="AutoFixture" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Client\Client.csproj" />
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\Host\Host.csproj" />
    </ItemGroup>
</Project>
