// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLModule.Data.Core.Migrations.SqlLite;

#nullable disable

namespace SQLModule.Data.Core.Migrations.SqlLite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20260622000002_RedesignAttempt")]
    partial class RedesignAttempt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedSql")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Domain.AttributeParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetaAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParameterDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetaAttributeId");

                    b.HasIndex("ParameterDefinitionId");

                    b.ToTable("AttributeParameterValues");
                });

            modelBuilder.Entity("Domain.CellValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DataRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetaAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataRecordId");

                    b.HasIndex("MetaAttributeId");

                    b.ToTable("CellValues");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetaTableId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetaTableId");

                    b.ToTable("DataRecords");
                });

            modelBuilder.Entity("Domain.DbmsDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsSystemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDatabase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvDatabaseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvPasswordKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvUserKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraEnvConfig")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbmsDictionaries");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MetaTableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhysicalTypeId")
                        .HasColumnType("TEXT");

                    b.Property<short>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetaTableId");

                    b.HasIndex("PhysicalTypeId");

                    b.ToTable("MetaAttributes");
                });

            modelBuilder.Entity("Domain.MetaRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteRule")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateRule")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceAttributeId");

                    b.HasIndex("TargetAttributeId");

                    b.ToTable("MetaRelationships");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetDbId");

                    b.ToTable("MetaTables");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhysicalTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Separator")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<short>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SqlFragment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuePrefix")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalTypeId");

                    b.ToTable("ParameterDefinitions");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbmsId");

                    b.ToTable("PhysicalTypes");
                });

            modelBuilder.Entity("Domain.SqlQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrictColumnOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StrictRowOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetDbId");

                    b.ToTable("SqlQueries");
                });

            modelBuilder.Entity("Domain.SqlTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<short>("DifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SqlQueryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SqlQueryId");

                    b.HasIndex("TargetDbId");

                    b.HasIndex("TopicId");

                    b.ToTable("SqlTasks");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbmsId");

                    b.ToTable("TargetDbs");
                });

            modelBuilder.Entity("Domain.TemplateObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TemplateObjects");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Domain.Attempt", b =>
                {
                    b.HasOne("Domain.SqlTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AttributeParameterValue", b =>
                {
                    b.HasOne("Domain.MetaAttribute", "MetaAttribute")
                        .WithMany()
                        .HasForeignKey("MetaAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ParameterDefinition", "ParameterDefinition")
                        .WithMany("AttributeParameterValues")
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaAttribute");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("Domain.CellValue", b =>
                {
                    b.HasOne("Domain.DataRecord", "DataRecord")
                        .WithMany("CellValues")
                        .HasForeignKey("DataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.MetaAttribute", "MetaAttribute")
                        .WithMany("CellValues")
                        .HasForeignKey("MetaAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataRecord");

                    b.Navigation("MetaAttribute");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.HasOne("Domain.MetaTable", "MetaTable")
                        .WithMany("DataRecords")
                        .HasForeignKey("MetaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaTable");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.HasOne("Domain.MetaTable", "MetaTable")
                        .WithMany("Attributes")
                        .HasForeignKey("MetaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PhysicalType", "PhysicalType")
                        .WithMany()
                        .HasForeignKey("PhysicalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetaTable");

                    b.Navigation("PhysicalType");
                });

            modelBuilder.Entity("Domain.MetaRelationship", b =>
                {
                    b.HasOne("Domain.MetaAttribute", "SourceAttribute")
                        .WithMany()
                        .HasForeignKey("SourceAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.MetaAttribute", "TargetAttribute")
                        .WithMany()
                        .HasForeignKey("TargetAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAttribute");

                    b.Navigation("TargetAttribute");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.HasOne("Domain.TargetDb", "TargetDb")
                        .WithMany("MetaTables")
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetDb");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.HasOne("Domain.PhysicalType", "PhysicalType")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("PhysicalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalType");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.HasOne("Domain.DbmsDictionary", "Dbms")
                        .WithMany("PhysicalTypes")
                        .HasForeignKey("DbmsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("Domain.SqlTask", b =>
                {
                    b.HasOne("Domain.SqlQuery", "SqlQuery")
                        .WithMany()
                        .HasForeignKey("SqlQueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.TargetDb", "TargetDb")
                        .WithMany()
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Topic", "Topic")
                        .WithMany("Tasks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SqlQuery");

                    b.Navigation("TargetDb");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.HasOne("Domain.DbmsDictionary", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.HasOne("Domain.Topic", "ParentTopic")
                        .WithMany("SubTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTopic");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.Navigation("CellValues");
                });

            modelBuilder.Entity("Domain.DbmsDictionary", b =>
                {
                    b.Navigation("PhysicalTypes");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.Navigation("CellValues");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("DataRecords");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.Navigation("AttributeParameterValues");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.Navigation("ParameterDefinitions");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.Navigation("MetaTables");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Navigation("SubTopics");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
