// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SQLModule.Data.Core.Migrations.PostgreSql;

#nullable disable

namespace SQLModule.Data.Core.Migrations.PostgreSql
{
    [DbContext(typeof(PostgreSqlDbContext))]
    partial class PostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.HasIndex("TaskId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Domain.AttributeParameterValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetaAttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParameterDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetaAttributeId");

                    b.HasIndex("ParameterDefinitionId");

                    b.ToTable("AttributeParameterValues");
                });

            modelBuilder.Entity("Domain.CellValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetaAttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataRecordId");

                    b.HasIndex("MetaAttributeId");

                    b.ToTable("CellValues");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetaTableId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetaTableId");

                    b.ToTable("DataRecords");
                });

            modelBuilder.Entity("Domain.DbmsDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DbmsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DbmsSystemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultDatabase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DefaultPort")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EnvDatabaseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EnvPasswordKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EnvUserKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtraEnvConfig")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DbmsDictionaries");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MetaTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhysicalTypeId")
                        .HasColumnType("uuid");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MetaTableId");

                    b.HasIndex("PhysicalTypeId");

                    b.ToTable("MetaAttributes");
                });

            modelBuilder.Entity("Domain.MetaRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DeleteRule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RelationshipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SourceAttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAttributeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdateRule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAttributeId");

                    b.HasIndex("TargetAttributeId");

                    b.ToTable("MetaRelationships");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetDbId");

                    b.ToTable("MetaTables");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PhysicalTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Separator")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("SqlFragment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ValuePrefix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValueSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalTypeId");

                    b.ToTable("ParameterDefinitions");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DbmsId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DbmsId");

                    b.ToTable("PhysicalTypes");
                });

            modelBuilder.Entity("Domain.SqlQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StrictColumnOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("StrictRowOrder")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SqlQueries");
                });

            modelBuilder.Entity("Domain.SqlTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<short>("DifficultyLevel")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SqlQueryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TaskText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SqlQueryId");

                    b.HasIndex("TargetDbId");

                    b.HasIndex("TopicId");

                    b.ToTable("SqlTasks");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DbmsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DbmsId");

                    b.ToTable("TargetDbs");
                });

            modelBuilder.Entity("Domain.TemplateObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TemplateObjects");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Domain.Attempt", b =>
                {
                    b.HasOne("Domain.SqlQuery", null)
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.SqlTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AttributeParameterValue", b =>
                {
                    b.HasOne("Domain.MetaAttribute", "MetaAttribute")
                        .WithMany()
                        .HasForeignKey("MetaAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ParameterDefinition", "ParameterDefinition")
                        .WithMany("AttributeParameterValues")
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaAttribute");

                    b.Navigation("ParameterDefinition");
                });

            modelBuilder.Entity("Domain.CellValue", b =>
                {
                    b.HasOne("Domain.DataRecord", "DataRecord")
                        .WithMany("CellValues")
                        .HasForeignKey("DataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.MetaAttribute", "MetaAttribute")
                        .WithMany("CellValues")
                        .HasForeignKey("MetaAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataRecord");

                    b.Navigation("MetaAttribute");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.HasOne("Domain.MetaTable", "MetaTable")
                        .WithMany("DataRecords")
                        .HasForeignKey("MetaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaTable");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.HasOne("Domain.MetaTable", "MetaTable")
                        .WithMany("Attributes")
                        .HasForeignKey("MetaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PhysicalType", "PhysicalType")
                        .WithMany()
                        .HasForeignKey("PhysicalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetaTable");

                    b.Navigation("PhysicalType");
                });

            modelBuilder.Entity("Domain.MetaRelationship", b =>
                {
                    b.HasOne("Domain.MetaAttribute", "SourceAttribute")
                        .WithMany()
                        .HasForeignKey("SourceAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.MetaAttribute", "TargetAttribute")
                        .WithMany()
                        .HasForeignKey("TargetAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAttribute");

                    b.Navigation("TargetAttribute");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.HasOne("Domain.TargetDb", "TargetDb")
                        .WithMany("MetaTables")
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetDb");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.HasOne("Domain.PhysicalType", "PhysicalType")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("PhysicalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalType");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.HasOne("Domain.DbmsDictionary", "Dbms")
                        .WithMany("PhysicalTypes")
                        .HasForeignKey("DbmsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("Domain.SqlTask", b =>
                {
                    b.HasOne("Domain.SqlQuery", "SqlQuery")
                        .WithMany()
                        .HasForeignKey("SqlQueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.TargetDb", "TargetDb")
                        .WithMany()
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Topic", "Topic")
                        .WithMany("Tasks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SqlQuery");

                    b.Navigation("TargetDb");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.HasOne("Domain.DbmsDictionary", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.HasOne("Domain.Topic", "ParentTopic")
                        .WithMany("SubTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTopic");
                });

            modelBuilder.Entity("Domain.DataRecord", b =>
                {
                    b.Navigation("CellValues");
                });

            modelBuilder.Entity("Domain.DbmsDictionary", b =>
                {
                    b.Navigation("PhysicalTypes");
                });

            modelBuilder.Entity("Domain.MetaAttribute", b =>
                {
                    b.Navigation("CellValues");
                });

            modelBuilder.Entity("Domain.MetaTable", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("DataRecords");
                });

            modelBuilder.Entity("Domain.ParameterDefinition", b =>
                {
                    b.Navigation("AttributeParameterValues");
                });

            modelBuilder.Entity("Domain.PhysicalType", b =>
                {
                    b.Navigation("ParameterDefinitions");
                });

            modelBuilder.Entity("Domain.TargetDb", b =>
                {
                    b.Navigation("MetaTables");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Navigation("SubTopics");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
